### ISSUE TITLE
API errors

### ISSUE THREAD

**Issue by Kdisimone** [jwoglom/tconnectsync#20] opened 2021-11-03 23:05 UTC
EDIT:  I see the note at the end of the readme page now.  This issue is moot. I'll close it as I think that was probably my issue for the one set of errors in the original post.

I'm certain this is user error BUT...can you please help me?

I'm getting this problem in the setup when I do the `tconnectsync --check-login` command

```
Kathryns-iMac:~ iMac4K$ tconnectsync --check-login
Logging in to t:connect ControlIQ API...
2021-11-03 15:52:26 INFO     Logging in to ControlIQApi...
Error occurred querying ControlIQ API: Error logging in to t:connect. Check your login credentials. (HTTP 200)

Logging in to t:connect WS2 API...
2021-11-03 15:52:26 INFO     Logging in to ControlIQApi...
Error occurred querying WS2 API: Error logging in to t:connect. Check your login credentials. (HTTP 200)

Logging in to t:connect Android API...
Error occurred querying Android API: Received HTTP 400 during login: {"statusCode":400,"status":400,"code":400,"message":"Max attempted logins exceeded.","name":"invalid_request"} (HTTP 400)

Logging in to Nightscout...
Error occurred querying Nightscout API: HTTPSConnectionPool(host='yournightscouturl', port=443): Max retries exceeded with url: /api/v1/status.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x102ca6f40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

API errors occurred. Please check the errors above.
```

*My .env file is located in the folder path I'm in
*I double checked my logins and passwords by logging in separately. Used copy and paste to avoid typos and really slowlllly checked spelling.

So someone want to give a second set of eyes to my .env file? Maybe that is wrong? Can I email it to someone privately?  

Last minute thought...will the API error appear using the --check-login if tconnect doesn't have any data in it for the current day? Seems like an unlikely error message that logins are failing, if it truly is a data-related issue, but thought I'd mention it anyways. My daughter's tconnect app stopped working 15 hours ago randomly and we are waiting for the last 15 hours to sync.

**Comment by Kdisimone** [comment] 2021-11-04 00:03
Hmm...switched to pipenv installation instead and that is working for API logins. So, I'm stumped why the original method isn't working, but I'll move on in the instructions. Onto the Supervisord part

**Comment by bewest** [comment] 2021-12-22 00:14
I'm experiencing same issue, using `pip3 install tconnectsync` and `tconnectsync` directly.

**Comment by kswick** [comment] 2021-12-22 03:13
I have seen this sometimes but not all the time. I also used the pip3 install option and I was able to run tconnectsync --check-login successfully earlier today. Now I'm getting this error despite having made no changes to the tconnectsync configuration. 

It is worth nothing that my t:connect mobile app (on Samsung Galaxy S21 running Android 12) is not uploading to my t:connect account. Currently the only way I have been able to upload data is to plug my pump into my computer and upload using the Tandem Uploader app so my data isn't always current. However, I just resynced and logged back into my t:connect account online and I'm still getting this error from tconnectsync.

**Comment by jwoglom** [comment] 2021-12-22 03:29
Want to make sure that everyone in this thread was experiencing the same issue here -- the original log output from @Kdisimone mentions two different errors:

> Error occurred querying Android API: Received HTTP 400 during login: {"statusCode":400,"status":400,"code":400,"message":"Max attempted logins exceeded.","name":"invalid_request"} (HTTP 400)

This appears to be some kind of ratelimit on Tandem's end, due to too many login attempts. Maybe caused by having tconnectsync running with invalid credentials for too long? 

> Error occurred querying Nightscout API: HTTPSConnectionPool(host='yournightscouturl', port=443): Max retries exceeded with url: /api/v1/status.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x102ca6f40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

This appears to be a failure to connect to the Nightscout server. Unless you sanitized your Nightscout URL in the log message, you likely just didn't change the literal `yournightscouturl` to the URL of your Nightscout instance.

@bewest @kswick which errors are you experiencing? Can you run tconnectsync with debug logging enabled (`tconnectsync --verbose`) and post the output here? You can remove your Nightscout URL and tconnect email. Alternatively please feel free to email me with your unsanitized logs and I'll take a look at them.

**Comment by kswick** [comment] 2021-12-22 04:01
@jwoglom A rate limit by Tandem had been my suspicion. I haven't yet figured out how long the lockout is for though. I've tried waiting an hour and I still get the `Max attempted logins exceeded.` error but I tried a day or 2 later and I got no API errors so I attempted the supervisor configuration and then promptly got the error again.

However, my nightscout url is correct (`NS_URL='https://kswick-nightscout.herokuapp.com/'`) as are my apisecret and Tandem credentials so I was wondering if the default nightscout url in the output might be a side effect of the Tandem errors but I haven't yet tried to follow that logic in the code to confirm that theory.

Here is the output from running with the `--verbose` option:
<pre><code>kristen_swick@instance-5:~/tconnectsync$ tconnectsync --verbose
2021-12-22 03:44:11 DEBUG    Set logging level to DEBUG
2021-12-22 03:44:11 INFO     Enabled features: BASAL, BOLUS, IOB
Processing data between 2021-12-21 03:44:11.750097 and 2021-12-22 03:44:11.750097 
2021-12-22 03:44:11 INFO     Downloading t:connect ControlIQ data
2021-12-22 03:44:11 DEBUG    Instantiating new ControlIQApi
2021-12-22 03:44:11 INFO     Logging in to ControlIQApi...
2021-12-22 03:44:11 DEBUG    Starting new HTTPS connection (1): tconnect.tandemdiabetes.com:443
2021-12-22 03:44:12 DEBUG    https://tconnect.tandemdiabetes.com:443 "GET /login.aspx?ReturnUrl=%2F HTTP/1.1" 200 33848
2021-12-22 03:44:12 DEBUG    https://tconnect.tandemdiabetes.com:443 "POST /login.aspx?ReturnUrl=%2F HTTP/1.1" 200 34297
Traceback (most recent call last):
  File "/home/kristen_swick/.local/bin/tconnectsync", line 8, in <module>
    sys.exit(main())
  File "/home/kristen_swick/.local/lib/python3.8/site-packages/tconnectsync/__init__.py", line 88, in main
    added = process_time_range(tconnect, nightscout, time_start, time_end, args.pretend, features=args.features)
  File "/home/kristen_swick/.local/lib/python3.8/site-packages/tconnectsync/process.py", line 52, in process_time_range
    raise e
  File "/home/kristen_swick/.local/lib/python3.8/site-packages/tconnectsync/process.py", line 43, in process_time_range
    ciqTherapyTimelineData = tconnect.controliq.therapy_timeline(time_start, time_end)
  File "/home/kristen_swick/.local/lib/python3.8/site-packages/tconnectsync/api/__init__.py", line 30, in controliq
    self._ciq = ControlIQApi(self.email, self.password)
  File "/home/kristen_swick/.local/lib/python3.8/site-packages/tconnectsync/api/controliq.py", line 24, in __init__
    self.login(email, password)
  File "/home/kristen_swick/.local/lib/python3.8/site-packages/tconnectsync/api/controliq.py", line 37, in login
    raise ApiLoginException(req.status_code, 'Error logging in to t:connect. Check your login credentials.')
tconnectsync.api.common.ApiLoginException: Error logging in to t:connect. Check your login credentials. (HTTP 200)</code></pre>
<pre><code>kristen_swick@instance-5:~/tconnectsync$ tconnectsync --verbose --check-login
2021-12-22 03:44:47 DEBUG    Set logging level to DEBUG
Logging in to t:connect ControlIQ API...
2021-12-22 03:44:47 DEBUG    Instantiating new ControlIQApi
2021-12-22 03:44:47 INFO     Logging in to ControlIQApi...
2021-12-22 03:44:47 DEBUG    Starting new HTTPS connection (1): tconnect.tandemdiabetes.com:443
2021-12-22 03:44:48 DEBUG    https://tconnect.tandemdiabetes.com:443 "GET /login.aspx?ReturnUrl=%2F HTTP/1.1" 200 33848
2021-12-22 03:44:48 DEBUG    https://tconnect.tandemdiabetes.com:443 "POST /login.aspx?ReturnUrl=%2F HTTP/1.1" 200 34297
Error occurred querying ControlIQ API: Error logging in to t:connect. Check your login credentials. (HTTP 200)

Logging in to t:connect WS2 API...
2021-12-22 03:44:48 DEBUG    Instantiating new WS2Api
2021-12-22 03:44:48 DEBUG    Instantiating new ControlIQApi
2021-12-22 03:44:48 INFO     Logging in to ControlIQApi...
2021-12-22 03:44:48 DEBUG    Starting new HTTPS connection (1): tconnect.tandemdiabetes.com:443
2021-12-22 03:44:48 DEBUG    https://tconnect.tandemdiabetes.com:443 "GET /login.aspx?ReturnUrl=%2F HTTP/1.1" 200 33848
2021-12-22 03:44:49 DEBUG    https://tconnect.tandemdiabetes.com:443 "POST /login.aspx?ReturnUrl=%2F HTTP/1.1" 200 34297
Error occurred querying WS2 API: Error logging in to t:connect. Check your login credentials. (HTTP 200)

Logging in to t:connect Android API...
2021-12-22 03:44:49 DEBUG    Instantiating new AndroidApi
2021-12-22 03:44:49 DEBUG    Starting new HTTPS connection (1): tdcservices.tandemdiabetes.com:443
2021-12-22 03:44:49 DEBUG    https://tdcservices.tandemdiabetes.com:443 "POST /cloud/oauth2/token HTTP/1.1" 400 110
Error occurred querying Android API: Received HTTP 400 during login: {"statusCode":400,"status":400,"code":400,"message":"Max attempted logins exceeded.","name":"invalid_request"} (HTTP 400)

Logging in to Nightscout...
2021-12-22 03:44:49 DEBUG    Starting new HTTPS connection (1): yournightscouturl:443
Error occurred querying Nightscout API: HTTPSConnectionPool(host='yournightscouturl', port=443): Max retries exceeded with url: /api/v1/status.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7febd40f4f70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

API errors occurred. Please check the errors above.</code></pre> 

And here is my .env file (with passwords removed):
<pre><code># Your credentials for t:connect
TCONNECT_EMAIL='kristen.swick@gmail.com'
TCONNECT_PASSWORD=''

# Your pump's serial number (numeric)
PUMP_SERIAL_NUMBER=900920

# URL and API secret for Nightscout
NS_URL='https://kswick-nightscout.herokuapp.com/'
NS_SECRET=''

# Current timezone of the pump
TIMEZONE_NAME='America/New_York'</code></pre>

P.S. Thank you so much for doing this! This is incredible! I'm excited that there is hope of keeping all my data in one place despite my recent switch to t:slim less than a week ago!

**Comment by bewest** [comment] 2021-12-22 17:33
The issue I experienced was fairly simple.  When using `tconnectsync` tool installed by `pip3`, it would not read the `.env` file.  The default values produce the logged output captured in the other tickets, most notably `yournightscouturl` used as the NS url.  Curiously, this value is used even when I export an `NS_URL` in the environment explicitly.

For some reason, using the `pip3 run` will read the `.env` file, at least when copied into the source directory.

**Comment by jwoglom** [comment] 2021-12-24 01:50
@bewest I updated the repo and published a new release to pypi with what I hope is a fix for this behavior. I presume what might be happening here is that, when you install tconnectsync via pip, it attempts to read a .env file in the folder containing the tconnectsync executable, rather than the current folder you're in. I added a new feature in that tconnectsync will attempt to load environment values from a `$HOME/.config/tconnectsync/.env` file, if present. If you put your configuration in .config/tconnectsync, I think that will work around this problem. I also ensured that environment variables properly override .env values.

**Comment by bewest** [comment] 2021-12-24 17:24
Thanks @jwoglom, makes sense.  IIRC, node js and openaps had similar issue, where we need to get `os.getcwd( )`.  I see your patches include this and more improvements.  I look forward to giving this a try and suspect it will cover the problem @Kdisimone and I ran into.

**Closed** 2023-06-11 04:50 UTC
Labels: setup help
