### ISSUE TITLE
Error: Cannot parse 2022-12-02+06:47:45.300389 00:00 as a valid ISO-8601 date

### ISSUE THREAD

**Issue by TimValishev** [jwoglom/tconnectsync#71] opened 2022-12-03 06:54 UTC
Man, thank you for the fast reaction to the previous one! Here's what I see in 0.8.7 (my Nightscout version is 14.2.5):

> 2022-12-03 06:47:45 INFO     Enabled features: BASAL, BOLUS
Processing data between 2022-12-02 06:47:45.300389 and 2022-12-03 06:47:45.300389
2022-12-03 06:47:45 INFO     Downloading t:connect ControlIQ data
2022-12-03 06:47:45 INFO     Logging in to ControlIQApi...
2022-12-03 06:47:46 INFO     Reported tconnect software version: t:connect 7.14.0.1
2022-12-03 06:47:48 INFO     Logged in to ControlIQApi successfully (expiration: 2022-12-03T14:47:46.367Z, in 7 hours, 59 minutes)
2022-12-03 06:47:48 INFO     Downloading t:connect therapy_events
2022-12-03 06:47:49 INFO     Last CGM reading from t:connect CIQ: 2022-12-02T16:57:24+04:00 (17 hours, 50 minutes ago)
2022-12-03 06:47:49 INFO     Last bolus from t:connect CIQ: 2022-12-02T18:12:48 (12 hours, 35 minutes ago)
2022-12-03 06:47:49 INFO     Last basal event from CIQ: {'time': '2022-12-02 17:00:53+04:00', 'delivery_type': 'profileDelivery', 'duration_mins': 1055.3833333333334, 'basal_rate': 1.0}
Traceback (most recent call last):
  File "/usr/local/bin/tconnectsync", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/tconnectsync/__init__.py", line 91, in main
    added = process_time_range(tconnect, nightscout, time_start, time_end, args.pretend, features=args.features)
  File "/usr/local/lib/python3.8/dist-packages/tconnectsync/process.py", line 143, in process_time_range
    added += ns_write_basal_events(nightscout, basalEvents, pretend=pretend, time_start=time_start, time_end=time_end)
  File "/usr/local/lib/python3.8/dist-packages/tconnectsync/sync/basal.py", line 109, in ns_write_basal_events
    last_upload = nightscout.last_uploaded_entry(BASAL_EVENTTYPE, time_start=time_start, time_end=time_end)
  File "/usr/local/lib/python3.8/dist-packages/tconnectsync/nightscout.py", line 82, in last_uploaded_entry
    ret = internal(True)
  File "/usr/local/lib/python3.8/dist-packages/tconnectsync/nightscout.py", line 73, in internal
    raise ApiException(latest.status_code, "Nightscout last_uploaded_entry response: %s" % latest.text)
tconnectsync.api.common.ApiException: Nightscout last_uploaded_entry response: <html>
  <head>
    <meta charset='utf-8'>
    <title>Error: Cannot parse 2022-12-02+06:47:45.300389 00:00 as a valid ISO-8601 date</title>
    <style>* {
  margin: 0;
  padding: 0;
  outline: 0;
}

body {
  padding: 80px 100px;
  font: 13px "Helvetica Neue", "Lucida Grande", "Arial";
  background: #ECE9E9 -webkit-gradient(linear, 0% 0%, 0% 100%, from(#fff), to(#ECE9E9));
  background: #ECE9E9 -moz-linear-gradient(top, #fff, #ECE9E9);
  background-repeat: no-repeat;
  color: #555;
  -webkit-font-smoothing: antialiased;
}
h1, h2 {
  font-size: 22px;
  color: #343434;
}
h1 em, h2 em {
  padding: 0 5px;
  font-weight: normal;
}
h1 {
  font-size: 60px;
}
h2 {
  margin-top: 10px;
}
ul li {
  list-style: none;
}
#stacktrace {
  margin-left: 60px;
}
</style>
  </head>
  <body>
    <div id="wrapper">
      <h1>Connect</h1>
      <h2><em>500</em> Error: Cannot parse 2022-12-02+06:47:45.300389 00:00 as a valid ISO-8601 date</h2>
      <ul id="stacktrace"><li> &nbsp; &nbsp;at /srv/nightscout-vps/lib/server/query.js:71:17</li><li> &nbsp; &nbsp;at Array.forEach (&lt;anonymous&gt;)</li><li> &nbsp; &nbsp;at enforceDateFilter (/srv/nightscout-vps/lib/server/query.js:62:28)</li><li> &nbsp; &nbsp;at create (/srv/nightscout-vps/lib/server/query.js:120:5)</li><li> &nbsp; &nbsp;at query_for (/srv/nightscout-vps/lib/server/treatments.js:121:12)</li><li> &nbsp; &nbsp;at Function.list (/srv/nightscout-vps/lib/server/treatments.js:115:13)</li><li> &nbsp; &nbsp;at /srv/nightscout-vps/lib/api/treatments/index.js:94:22</li><li> &nbsp; &nbsp;at Layer.handle [as handle_request] (/srv/nightscout-vps/node_modules/express/lib/router/layer.js:95:5)</li><li> &nbsp; &nbsp;at next (/srv/nightscout-vps/node_modules/express/lib/router/route.js:137:13)</li><li> &nbsp; &nbsp;at Route.dispatch (/srv/nightscout-vps/node_modules/express/lib/router/route.js:112:3)</li></ul>
    </div>
  </body>
</html>
 (HTTP 500)

**Comment by LvnInLevis** [comment] 2022-12-07 02:00
Also getting this error, and not seeing bolus doses on NS.

**Comment by kswick** [comment] 2022-12-12 19:50
I'm getting this same error with v0.8.7 (pip install in google cloud VM). I then experimented in another VM instance with a pipenv install. I confirmed I got the same error with v0.8.7 with only the BOLUS feature specified. Then I checked out the v0.8.5 tag and I still got the same error. Then I checked out the 0.8.3 tag and I do NOT get any errors and I got bolus data in nightscout. So this appears to be related to a change between v0.8.3 and v0.8.5.

A temporary workaround for those running into problems may be to revert back to v0.8.3 for now (assuming the issues resolved in v0.8.5 and v0.8.7 weren't causing you problems before).

**Comment by jlecount** [comment] 2022-12-13 01:05
Changing this resolved it for me -- I'm not opening a PR because I don't know the cases in which we want the T-substitution or what the original purpose was.  However the workaround that works for me is:

```
                ret = internal(False)
                if ret is None and (time_start or time_end):
                        **ret = internal(False)** # this is line 82 and is False instead of True like all the others.  This disconcerts me.

```

**Comment by jwoglom** [comment] 2022-12-13 03:40
All -- attempted to work around this case, please take a look with the latest version (v0.8.8). Unfortunately different (older?) versions of Nightscout seem to be inconsistent with timestamp format -- e.g., a version I tested with returns no results when entering an invalid timestamp instead of a 5xx error.

**Comment by jlecount** [comment] 2022-12-13 03:55
Would you be open to a PR from me using https://dateutil.readthedocs.io/en/stable/parser.html to parse dates?  It's worked well for me in the past when one needs some flexibility in date parsing.

Regardless, I'll pull your branch and give it a shot.  Thank you!

**Comment by jwoglom** [comment] 2022-12-14 19:57
@diabetesman I just manually ran the workflow action to push the new release to pypi; check to see that it's available in a few minutes

**Comment by jwoglom** [comment] 2023-01-07 06:01
@TimValishev @LvinInLevis @kswick @jlecount @diabetesman Just want to confirm that everything is working okay for you all with the latest build. If so, I will close this issue.

**Comment by jlecount** [comment] 2023-01-07 17:22
Thanks so much, @TimValishev  - I'll give it a shot today...

**Comment by jlecount** [comment] 2023-01-07 20:08
Yep, this is working great -- thanks again!

**Comment by diabetesman** [comment] 2023-01-07 20:33
Hi, I tested it with v0.8.8 and it was working and I just upgraded to
v0.8.10 and it's still working. Thanks for fixing it.

Thanks

**Comment by jwoglom** [comment] 2023-01-07 20:33
Great, I will close the issue.

**Closed by jwoglom** 2023-01-07 20:33 UTC

**Comment by vincepf** [comment] 2023-05-29 18:21
I too have this same issue on 0.9.3 running on python 3.9 on an openSUSE machine. My nightscout version is 14.2.5

**Comment by ramboozer** [comment] 2023-06-20 22:19
I am also having an issue. Latest version of NS & tconnectsync.

**Comment by jwoglom** [comment] 2023-06-20 22:37
@clegoues @vincepf @ramboozer can you give a full traceback of the error and also run with --check-login? You can reply here or email this to tconnectsync at wogloms.net

**Comment by vincepf** [comment] 2023-06-21 02:20
@jwoglom  Thank you for the reply and all of your tremendous work on this. It's really a lifesaver for our family. I apologize; the last time I tried it a few days ago it had the error mentioned; as of 6/20/23 22:19 it does not and appears to be working properly. Perhaps it was a t:connect site issue?

**Comment by ramboozer** [comment] 2023-06-22 17:25
Attached is a copy of the log.
[tconnectsync-check-output.log](https://github.com/jwoglom/tconnectsync/files/11837562/tconnectsync-check-output.log)

**Comment by ramboozer** [comment] 2023-06-25 14:50
Pretty much just appears from what ive seen that / been reading. 
2023-06-21+13:42:11.800532 00:00 needs to be changed to 2023-06-21T13:42:11.800532Z to be a valid ISO String.

**Comment by ramboozer** [comment] 2023-06-26 01:35
Appears that TSlim app on my phone auto logged me out. I logged back in and all the errors went away. I imagine the data wasn't being populated.

**Comment by starbuck93** [comment] 2024-01-18 22:35
-- tconnectsync 0.9.6 via docker-compose on unraid. 

@jwoglom I'm now seeing this error. It appears to be a Nightscout issue? The GET request is asking for `last_uploaded_entry` and Nightscout returns HTTP 500 `Error: Cannot parse 2024-01-17+22:12:13.988501 00:00 as a valid ISO-8601 date` 

A quick Google search also shows that is not a valid ISO-8601 date.

tconnectsync appears to be able to POST data alright since Nightscout is returning 200's to that part in the logs.

Similar to ramboozer, last week-ish I was auto logged out as well but now I'm getting this error. I logged into t:connect and it appears to have up-to-date data right now. As does the Android app.

I've prepared a log file if that would be helpful.

**Comment by jwoglom** [comment] 2024-01-22 16:16
@starbuck93 I think the root cause of this problem is that some versions of Nightscout are liberal in what timestamp format they accept from clients, and some are not. I haven't completely tracked this down. Personally, I'm still running a several years old version of Nightscout which doesn't help matters in my testing. However, tconnectsync _should_ now detect this error and try again with a modified timestamp format if it detects the problem having occurred. So that might be why you see this problem in the log but the data eventually reconciled into Nightscout. Let me know if it stops working again.
